"""System state and event names."""

from __future__ import annotations

from enum import Enum


class SystemState(str, Enum):
    IDLE = "IDLE"
    SCAN = "SCAN"
    DELAY_COMPENSATION = "DELAY_COMPENSATION"
    TRACKING = "TRACKING"
    SAFE_HOLD = "SAFE_HOLD"
    LIMITED_RESCAN = "LIMITED_RESCAN"
    CENTERING = "CENTERING"
    ERROR = "ERROR"


class Event(str, Enum):
    TRACK_COMMAND = "TRACK_COMMAND"
    STOP_COMMAND = "STOP_COMMAND"
    CENTER_COMMAND = "CENTER_COMMAND"
    REDETECT_COMMAND = "REDETECT_COMMAND"
    DETECTION_LOCKED = "DETECTION_LOCKED"
    SCAN_FAILED = "SCAN_FAILED"
    SYNC_READY = "SYNC_READY"
    TRACK_OK = "TRACK_OK"
    SENSOR_ANOMALY = "SENSOR_ANOMALY"
    COMMS_DELAY = "COMMS_DELAY"
    RECOVERED = "RECOVERED"
    RESCAN_REQUIRED = "RESCAN_REQUIRED"
    RESCAN_SUCCESS = "RESCAN_SUCCESS"
    TIMEOUT = "TIMEOUT"
    CENTERED = "CENTERED"
    CALIBRATION_ERROR = "CALIBRATION_ERROR"
